# Site settings
title: Personal Website of Sangwon Park
description: The Personal Website of Sangwon Park. Here, you can find Sangwon Park's bio, projects, and contact info.
# baseurl:  
# url: "https://sangwonparkk.github.io" 

# User settings
username: Sangwon Park
user_description: Welcome! I am currently a sophmore student at the University of Hong Kong, studying computer science.
user_title: Student
email: swpark@hku.hk
twitter_username: swpark93
github_username:  sangwonparkk

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
